version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
    groups:
      periodic-updates:
        patterns:
          - "*"
        update-types:
          - "major"
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
