#!/usr/bin/env python3
"""
Script to generate AirlinesData.kt from opentraveldata CSV.

Usage:
    python scripts/generate_airlines.py [output_path]

Output path defaults to: app/src/main/java/com/tuxy/airo/data/AirlinesData.kt
"""

import csv
import urllib.request
import re
import sys
from datetime import datetime
from pathlib import Path


def download_and_parse_csv(url: str) -> dict[str, str]:
    """Download and parse the opentraveldata airlines CSV."""
    print(f"Downloading CSV from: {url}")

    response = urllib.request.urlopen(url)
    data = response.read().decode('utf-8')

    lines = data.strip().split('\n')
    reader = csv.reader(lines, delimiter='^')
    header = next(reader)

    print(f"CSV has {len(lines)} lines")

    # Only valid IATA codes (2 uppercase letters)
    airlines: dict[str, str] = {}
    iata_pattern = re.compile(r'^[A-Z]{2}$')

    for row in reader:
        if len(row) >= 8:
            code = row[5].strip()  # 2char_code (index 5)
            name = row[7].strip()  # name (index 7)
            if iata_pattern.match(code) and name:
                if code not in airlines:
                    airlines[code] = name

    print(f"Found {len(airlines)} airlines")
    return airlines


def generate_kotlin(airlines: dict[str, str], timestamp: str) -> str:
    """Generate Kotlin code for AirlinesData.kt."""
    content = f'''package com.tuxy.airo.data

/**
 * Auto-generated airline data from opentraveldata. DO NOT MODIFY: AUTOGENERATED
 * Generated at: {timestamp}
 * Total airlines: {len(airlines)}
 */
object AirlinesData {{
    val airlines: Map<String, String> = mapOf(
'''

    for code in sorted(airlines.keys()):
        name = airlines[code].replace('"', '\\"').replace("'", "\\'")
        content += f'        "{code}" to "{name}",\n'

    content += '''    )
}
'''
    return content


def main():
    url = "https://raw.githubusercontent.com/opentraveldata/opentraveldata/master/opentraveldata/optd_airline_best_known_so_far.csv"

    if len(sys.argv) > 1:
        output_path = Path(sys.argv[1])
    else:
        output_path = Path(__file__).parent.parent / "app/src/main/java/com/tuxy/airo/data/AirlinesData.kt"

    airlines = download_and_parse_csv(url)
    timestamp = datetime.now().isoformat()
    kotlin_code = generate_kotlin(airlines, timestamp)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    _ = output_path.write_text(kotlin_code)

    print(f"Wrote {len(kotlin_code)} bytes to {output_path}")
    print(f"Total airlines: {len(airlines)}")


if __name__ == "__main__":
    main()
